# portainer-ingress-tls.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-gue
spec:
  secretName: app-gue-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: <domain>
  dnsNames:
    - <domain>
  issuerRef:
    name: letsencrypt-cluster
    kind: ClusterIssuer